version: '3.3'

services:
  web:
    build: .
    hostname: web
    command: ./manage.py runserver 0.0.0.0:${APP_PORT:-8000}
    volumes:
      - ${HOME}/Desktop:/root/Desktop:ro
      - .:/code
      - ./.data/services/web/bash_history:/root/.bash_history
      - ./.data/services/web/ipython/:/root/.ipython
    depends_on:
      - db
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"

  db:
    image: postgres
